colinin/abp-next-admin

- aspnet-core/services/account/AuthServer.Host/AuthIdentityServerModule.cs
- aspnet-core/services/account/AuthServer.Host/Microsoft/Extensions/DependencyInjection/SameSiteCookiesServiceCollectionExtensions.cs
> Fixed logon failure due to Chrome privacy policy update

- aspnet-core/modules/platform/LINGYUN.Platform.Application.Contracts/LINGYUN/Platform/Localization/ApplicationContracts/zh-Hans.json
- aspnet-core/modules/platform/LINGYUN.Platform.Domain/LINGYUN/Platform/PlatformDataSeedContributor.cs
- vueJs/debug.log
- vueJs/src/api/api-resources.ts
- vueJs/src/api/clients.ts
- vueJs/src/api/identity-server4.ts
- vueJs/src/views/container/menus/components/CreateOrUpdateMenuDialog.vue
1、增加Api Scope的预置菜单数据；
2、修复菜单编辑页在非编辑状态也会自动变更组件地址的问题；
3、修复Api定义中的一些错误
> Deal with some problems

- vueJs/.env.development
- vueJs/src/App.vue
- vueJs/src/api/dynamic-api.ts
- vueJs/src/api/identity-server4.ts
- vueJs/src/api/types.ts
- vueJs/src/mixins/HttpProxyMiXin.ts
- vueJs/src/store/index.ts
- vueJs/src/store/modules/http-proxy.ts
- vueJs/src/views/admin/identityServer/client/index.vue
Use in the current version is not recommended and will be optimized in conjunction with gateways in the future
> sopport abp dynamic api proxy

- aspnet-core/modules/common/LINGYUN.Abp.EventBus.CAP/LINGYUN/Abp/EventBus/CAP/AbpCAPEventBusModule.cs
- aspnet-core/modules/common/LINGYUN.Abp.Hangfire.Dashboard/LINGYUN/Abp/Hangfire/Dashboard/AbpHangfireDashboardModule.cs
- aspnet-core/modules/common/LINGYUN.Abp.Localization.Dynamic/LINGYUN/Abp/Localization/Dynamic/DynamicLocalizationInitializeService.cs
- aspnet-core/modules/common/LINGYUN.Abp.Notifications.Sms/LINGYUN/Abp/Notifications/Sms/AbpNotificationsSmsModule.cs
- aspnet-core/modules/common/LINGYUN.Abp.Notifications/LINGYUN/Abp/Notifications/AbpNotificationModule.cs
- aspnet-core/modules/oss-management/LINGYUN.Abp.BlobStoring.OssManagement/README.md
- aspnet-core/modules/wechat/LINGYUN.Abp.Notifications.WeChat.MiniProgram/LINGYUN/Abp/Notifications/WeChat/MiniProgram/AbpNotificationsWeChatMiniProgramModule.cs
- aspnet-core/modules/workflow/LINGYUN.Abp.WorkflowCore/LINGYUN/Abp/WorkflowCore/AbpWorkflowCoreModule.cs
- aspnet-core/services/LY.MicroService.WorkflowManagement.HttpApi.Host/WorkflowManagementHttpApiHostModule.Configure.cs
- build/modules.dependencies.json
IServiceCollection.ExecutePreConfiguredActions extension should be in the service before starting
> fix: IServiceCollection.ExecutePreConfiguredActions extension should be in the service before starting

- aspnet-core/services/LY.MicroService.BackendAdmin.HttpApi.Host/EventBus/Handlers/TenantSynchronizer.cs
Make tenant permission initialization independent of a specific database provider
> feat(permissions): Make tenant permission initialization independent of a specific database provider

- aspnet-core/modules/oss-management/LINGYUN.Abp.OssManagement.FileSystem/LINGYUN/Abp/OssManagement/FileSystem/FileSystemOssContainer.cs
- aspnet-core/modules/task-management/LINGYUN.Abp.BackgroundTasks.ExceptionHandling/LINGYUN.Abp.BackgroundTasks.ExceptionHandling.csproj
- aspnet-core/modules/task-management/LINGYUN.Abp.BackgroundTasks.ExceptionHandling/LINGYUN/Abp/BackgroundTasks/ExceptionHandling/AbpBackgroundTasksExceptionHandlingModule.cs
- aspnet-core/modules/task-management/LINGYUN.Abp.BackgroundTasks.ExceptionHandling/LINGYUN/Abp/BackgroundTasks/ExceptionHandling/JobFailedNotifierProvider.cs
> 修复文件系统检索索引可能越界问题

- aspnet-core/services/LY.MicroService.RealtimeMessage.HttpApi.Host/EventBus/Distributed/ChatMessageEventHandler.cs
- aspnet-core/services/LY.MicroService.RealtimeMessage.HttpApi.Host/EventBus/Distributed/NotificationEventHandler.cs
- aspnet-core/services/LY.MicroService.RealtimeMessage.HttpApi.Host/LY.MicroService.RealtimeMessage.HttpApi.Host.csproj
- aspnet-core/services/LY.MicroService.RealtimeMessage.HttpApi.Host/MultiTenancy/TenantConfigurationCache.cs
- aspnet-core/services/LY.MicroService.RealtimeMessage.HttpApi.Host/RealtimeMessageHttpApiHostModule.Configure.cs
- aspnet-core/services/LY.MicroService.RealtimeMessage.HttpApi.Host/RealtimeMessageHttpApiHostModule.cs
- aspnet-core/services/LY.MicroService.RealtimeMessage.HttpApi.Host/appsettings.Development.json
Ensure that message queue processing completes regardless of whether the message was successfully processed
> Ensure that message queue processing completes regardless of whether the message was successfully processed

- apps/vue/src/components/Table/src/BasicTable.vue
- apps/vue/src/components/Table/src/components/TableAlert.vue
- apps/vue/src/components/Table/src/hooks/useTableAlert.ts
Fix the TableAlert component at #723
> Fix the TableAlert component

- aspnet-core/LINGYUN.MicroService.All.sln
- aspnet-core/modules/common/LINGYUN.Abp.Location.Baidu/LINGYUN.Abp.Location.Baidu.csproj
- aspnet-core/modules/common/LINGYUN.Abp.Location.Baidu/LINGYUN/Abp/Location/Baidu/AbpBaiduLocationModule.cs
- aspnet-core/modules/common/LINGYUN.Abp.Location.Baidu/LINGYUN/Abp/Location/Baidu/BaiduLocationHttpClient.cs
- aspnet-core/modules/common/LINGYUN.Abp.Location.Tencent/LINGYUN.Abp.Location.Tencent.csproj
- aspnet-core/modules/common/LINGYUN.Abp.Location.Tencent/LINGYUN/Abp/Location/Tencent/AbpTencentLocationModule.cs
- aspnet-core/modules/common/LINGYUN.Abp.Location.Tencent/LINGYUN/Abp/Location/Tencent/TencentLocationHttpClient.cs
- aspnet-core/modules/message/LINGYUN.Abp.MessageService.EntityFrameworkCore/LINGYUN/Abp/MessageService/Chat/EfCoreMessageRepository.cs
- aspnet-core/modules/platform/LINGYUN.Platform.Domain/LINGYUN.Platform.Domain.csproj
- aspnet-core/modules/pushplus/LINGYUN.Abp.PushPlus/LINGYUN.Abp.PushPlus.csproj
- aspnet-core/modules/pushplus/LINGYUN.Abp.PushPlus/LINGYUN/Abp/PushPlus/AbpPushPlusModule.cs
- aspnet-core/modules/wechat/LINGYUN.Abp.WeChat/LINGYUN.Abp.WeChat.csproj
- aspnet-core/modules/wechat/LINGYUN.Abp.WeChat/LINGYUN/Abp/WeChat/AbpWeChatModule.cs
- aspnet-core/modules/wx-pusher/LINGYUN.Abp.WxPusher/LINGYUN.Abp.WxPusher.csproj
- aspnet-core/modules/wx-pusher/LINGYUN.Abp.WxPusher/LINGYUN/Abp/WxPusher/AbpWxPusherModule.cs
* Unreference the **Volo.Abp.Json.Newtonsoft** package.
* Remove the user history message sql statement.
> Fix multiple issues

- aspnet-core/modules/common/LINGYUN.Abp.Location.Baidu/LINGYUN/Abp/Location/Baidu/BaiduLocationHttpClient.cs
- aspnet-core/modules/common/LINGYUN.Abp.Location.Baidu/LINGYUN/Abp/Location/Baidu/Utils/BaiduAKSNCaculater.cs
- aspnet-core/tests/LINGYUN.Abp.Location.Baidu.Tests/LINGYUN/Abp/Location/Baidu/BaiduLocationResolveProviderTests.cs
> fix(location): baidu sn caculate

- aspnet-core/modules/localization/LINGYUN.Abp.AspNetCore.Mvc.Localization/LINGYUN/Abp/AspNetCore/Mvc/Localization/TextAppService.cs
- aspnet-core/modules/lt/LINGYUN.Abp.LocalizationManagement.Application/LINGYUN/Abp/LocalizationManagement/ResourceAppService.cs
querying the list of languages requires loading dynamic resources.
> fix(localization): querying the list of languages requires loading dynamic resources.

- aspnet-core/migrate-database.bat
- aspnet-core/migrate-db-cmd.bat
- aspnet-core/modules/platform/LINGYUN.Platform.Domain.Shared/LINGYUN/Platform/Localization/Resources/zh-Hans.json
- aspnet-core/start-all-service.bat
- gateways/web/LY.MicroService.ApiGateway/appsettings.Development.json
修改启用所有服务的bat文件，中间增加时间间隔，提升启动速度
修改bat文件增加标题及生成时的项目提示，方便查看
增加缺少的本地化文字
修改single项目的连接字符串
> 主要增加数据库迁移bat命令及修改service命令更人性化

- README.en.md
- README.md
Edit readme.md, add hosts config
> Edit readme.md, add hosts config

- aspnet-core/modules/task-management/LINGYUN.Abp.BackgroundTasks.Quartz/LINGYUN/Abp/BackgroundTasks/Quartz/QuartzJobScheduler.cs
> fix(tasks): Stops a job in execution upon deletion

- aspnet-core/framework/logging/LINGYUN.Abp.Logging.Serilog.Elasticsearch/LINGYUN/Abp/AuditLogging/Serilog/Elasticsearch/SerilogElasticsearchLoggingManager.cs
> Fix the serilog log level mapping

- aspnet-core/LINGYUN.MicroService.TaskManagement.sln
- aspnet-core/modules/task-management/LINGYUN.Abp.BackgroundTasks.Jobs/LINGYUN/Abp/BackgroundTasks/Jobs/ServiceInvocationJob.cs
- aspnet-core/services/LY.MicroService.TaskManagement.HttpApi.Host/LY.MicroService.TaskManagement.HttpApi.Host.csproj
- aspnet-core/services/LY.MicroService.TaskManagement.HttpApi.Host/TaskManagementHttpApiHostModule.cs
- aspnet-core/services/LY.MicroService.TaskManagement.HttpApi.Host/appsettings.Development.json
> fix(jobs): fix ServiceInvocationJob

- aspnet-core/framework/dynamic-queryable/LINGYUN.Abp.Dynamic.Queryable.Application.Contracts/LINGYUN/Abp/Dynamic/Queryable/IDynamicQueryableAppService.cs
- aspnet-core/framework/dynamic-queryable/LINGYUN.Abp.Dynamic.Queryable.Application/LINGYUN/Abp/Dynamic/Queryable/DynamicQueryableAppService.cs
- aspnet-core/framework/dynamic-queryable/LINGYUN.Abp.Dynamic.Queryable.HttpApi/LINGYUN/Abp/Dynamic/Queryable/DynamicQueryableControllerBase.cs
> refactor(dynamic-queryable): rename search method

- aspnet-core/framework/data-protection/LINGYUN.Abp.DataProtection.EntityFrameworkCore/LINGYUN/Abp/DataProtection/EntityFrameworkCore/AbpDataProtectionDbContext.cs
> fix(migrations): 修复迁移时DI容器不可用(#1011)

- .gitignore
- apps/vben5/scripts/turbo-run/bin/turbo-run.mjs
- apps/vben5/scripts/vsh/bin/vsh.mjs
> fix(vben):修补scripts缺失bin目录文件

- aspnet-core/modules/account/LINGYUN.Abp.Account.Web.IdentityServer/Pages/Account/IdentityServerLoginModel.cs
- rename expose services: `IdentityServerLoginModel`
> fix(identity-server): Fix the type export error

- aspnet-core/modules/account/LINGYUN.Abp.Account.Web/Pages/Account/Login.cshtml
- aspnet-core/modules/account/LINGYUN.Abp.Account.Web/Pages/Account/Register.cshtml
- The redirect to register link is placed above the login button
- The redirect to login link is placed above the registration button
> perf(account): Optimize the unregistered/logged-in prompt

- aspnet-core/modules/platform/LINGYUN.Abp.UI.Navigation.VueVbenAdmin5/LINGYUN/Abp/UI/Navigation/VueVbenAdmin5/AbpUINavigationVueVbenAdmin5NavigationDefinitionProvider.cs
- add cache menu icon
- add openapi menu icon
> feat(platform): add missing vben5 route icon

- apps/vben5/packages/@abp/identity/src/components/users/UserModal.vue
- apps/vben5/packages/@abp/identity/src/components/users/UserTable.vue
- apps/vben5/packages/@abp/identity/src/types/users.ts
- 用户Dto增加 `accessFailedCount` 字段
- 增加用户详情标签页
- 用户列表增加邮件验证标签
- 用户列表增加手机号验证标签
> feat(vben5): 增强用户信息

- apps/vben5/packages/@abp/platform/src/components/menus/MenuDrawer.vue
> fix(vben5): 修复编辑菜单没有重置表单

- aspnet-core/services/LY.AIO.Applications.Single/Pages/Account/TwoFactorSupportedLoginModel.cs
- add the missing component dependencies
> fix(aio): fix login page

- build/build-aspnetcore-build-sln.ps1
- build/build-aspnetcore-publish-sln.ps1
> ci: update build scipt

- apps/vben5/packages/@abp/account/src/components/MySetting.vue
- apps/vben5/packages/@abp/account/src/components/components/BasicSettings.vue
> fix(vben5): Fixed the concurrent error in updating profile

- apps/vben5/apps/app-antd/package.json
- apps/vben5/packages/@abp/account/package.json
- apps/vben5/packages/@abp/auditing/package.json
- apps/vben5/packages/@abp/components/package.json
- apps/vben5/packages/@abp/core/package.json
- apps/vben5/packages/@abp/data-protection/package.json
- apps/vben5/packages/@abp/demo/package.json
- apps/vben5/packages/@abp/features/package.json
- apps/vben5/packages/@abp/gdpr/package.json
- apps/vben5/packages/@abp/identity/package.json
- apps/vben5/packages/@abp/localization/package.json
- apps/vben5/packages/@abp/notifications/package.json
- apps/vben5/packages/@abp/openiddict/package.json
- apps/vben5/packages/@abp/oss/package.json
- apps/vben5/packages/@abp/permissions/package.json
- apps/vben5/packages/@abp/platform/package.json
- apps/vben5/packages/@abp/request/package.json
- apps/vben5/packages/@abp/saas/package.json
- apps/vben5/packages/@abp/settings/package.json
- apps/vben5/packages/@abp/signalr/package.json
- apps/vben5/packages/@abp/tasks/package.json
- apps/vben5/packages/@abp/text-templating/package.json
- apps/vben5/packages/@abp/ui/package.json
- apps/vben5/packages/@abp/webhooks/package.json
- Update the package version to 9.2.0
> chore(vben5): Update package.json

- apps/vben5/packages/@abp/ui/src/components/vxe-table/use-vxe-grid.ts
- apps/vben5/packages/@abp/ui/src/components/vxe-table/use-vxe-grid.vue
- apps/vben5/packages/effects/plugins/src/vxe-table/use-vxe-grid.vue
- apps/vben5/pnpm-workspace.yaml
- update `vxe-table` to `^4.14.4`
- update `vxe-pc-ui` to `^4.7.12`
- rewrite the `commitProxy` `initial` args
> fix: fixed #1277

- aspnet-core/modules/permissions-management/LINGYUN.Abp.PermissionManagement.Application/LINGYUN/Abp/PermissionManagement/IMultiplePermissionManager.cs
- aspnet-core/modules/permissions-management/LINGYUN.Abp.PermissionManagement.Application/LINGYUN/Abp/PermissionManagement/MultiplePermissionManager.cs
- aspnet-core/modules/permissions-management/LINGYUN.Abp.PermissionManagement.Application/LINGYUN/Abp/PermissionManagement/PermissionAppService.cs
- aspnet-core/modules/permissions-management/LINGYUN.Abp.PermissionManagement.Application/LINGYUN/Abp/PermissionManagement/PermissionChangeState.cs
- Through ` IMultiplePermissionManager ` set permissions in batches
> perf(permissions): Optimize the performance issue of batch setting permissions
